package mk.sekuloski.success

enum class ExpenseType {
    BILL, GAMING_GEAR, MUSIC_GEAR, SPORTS_GEAR, CLOTHES, TAKEAWAY_FOOD, FOOD_FOR_HOME,
    OUTSIDE_ACTIVITY, HANGING_OUT, FOOTBALL, TOOLS, FURNITURE, WHISKEY, GROCERIES, HOLIDAY,
    DEBT, MEDICAL
}

enum class PaymentType {
    SINGLE_PAYMENT, THREE_MONTHS, SIX_MONTHS, CREDIT
}